### ISSUE TITLE
SVGs not supported in grpc selection screen

### ISSUE THREAD

**Issue by grod220** [prax-wallet/web#112] opened 2024-07-18 15:51 UTC
The [registry globals](https://github.com/prax-wallet/registry/blob/main/registry/globals.json) had a svg image (https://github.com/prax-wallet/registry/pull/58), however, there were issues with Prax displaying svgs in the grpc selection screen. Only png's are currently working (https://github.com/prax-wallet/registry/pull/59). 

We should investigate how the grpc selection screen is handling svgs and ensure it can display that format correctly.

**Comment by j0nl1** [comment] 2024-07-19 10:18
SVGs works well in grpc selection. The issue is `silent-validator.svg` image is not a valid svg, it doesn't include XML tag and that's why is treated like a broken image in the grpc selection view.

You could check the code here: https://github.com/prax-wallet/registry/blob/main/images/silent-validator.svg?short_path=db5688a

compared with: https://github.com/prax-wallet/registry/blob/main/images/starling-cybernetics.svg?short_path=5139b01

I can confirm that adding the missing node, it works well.

**Comment by VanishMax** [comment] 2024-07-22 14:20
Agree with @j0nl1, this SVG is not enough for Chrome to render correctly. It can be fixed by adding the `xmlns="http://www.w3.org/2000/svg"` attribute to the `svg` tag. Since the broken SVG was changed by a PNG file, this issue is not relevant anymore. cc @grod220

**Closed** 2024-07-22 14:32 UTC
Labels: bug
